name: DigiCert Code Scan

on:
  workflow_dispatch:

jobs:
  analyze:
    name: DigiCert Code Monitoring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: digicert/digicert-code-monitoring-action@copilot/copilotadd-dc-release-id-input
        with:
          host: "https://lucila-brashier-paxton.ngrok-free.dev"
          api-key: ${{ secrets.STAGEAZ_API_KEY }}
          name: T-7-new-github-action-7
          tag: new-github-action-7
          with-release: "true"
          dc-release-id: a7e414d5-8456-4931-96b1-0cdb2bd4c0c7
          digicert-cdn: "https://pki-downloads.digicert.com/stm/snapshot/stmclients"
          use-github-caching-service: "true"
          use-binary-sha256-checksum: "true"