name: DigiCert Code Scan

on:
  workflow_dispatch:

jobs:
  analyze:
    name: DigiCert Code Monitoring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: digicert/digicert-code-monitoring-action@v2-dev
        with:
          host: "https://lucila-brashier-paxton.ngrok-free.dev"
          api-key: ${{ secrets.STAGEAZ_API_KEY }}
          name: T-new-github-action-1
          tag: new-github-action-1
          with-release: "true"
          dc-release-id: ec146f18-f866-4ee0-acde-921b7414d112
          digicert-cdn: "https://pki-downloads.digicert.com/stm/snapshot/stmclients"
          use-github-caching-service: "true"
          use-binary-sha256-checksum: "true"